--- #YAML:1.0
name:                File-MMagic-XS
version:             0.09
abstract:            Guess File Type With XS (a la mod_mime_magic)
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Daisuke Maki <daisuke@endeworks.jp>
